name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.145.0'

      - name: Build site
        run: hugo --minify
        

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true

      - name: Debug Build Output
        run: |
          echo "Contents of public folder:"
          ls -R public
          echo "Contents of themes folder:"
          ls -R themes
        
      - name: Check Hugo Version
        run: hugo version
        
      - name: Check Hugo Config
        run: cat hugo.yaml
